default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: email_cleaner_development

test:
  <<: *default
  database: email_cleaner_test

production:
  <<: *default
  database: email_cleaner_production
  username: email_cleaner
  password: <%= ENV["EMAIL_CLEANER_DATABASE_PASSWORD"] %>
